const { Auto, Foglalas, Ugyfel, AutoKibe } = require('../models');
const { Op } = require('sequelize');

exports.getStats = async (req, res) => {
    try {
        const today = new Date().toISOString().slice(0, 10);

        const osszesAuto = await Auto.count();
        const elerhetoAuto = await Auto.count({ where: { elerheto: true, berleheto: true } });
        const aktivFoglalas = await Foglalas.count({
            where: {
                foglalaskezdete: { [Op.lte]: today },
                foglalas_vege: { [Op.gte]: today }
            }
        });

        // Sum revenue for today (or total? Spec said "Mai bevétel" which implies transactions today)
        // Or revenue generated by active bookings today (pro-rated)?
        // Simplest: Sum 'Ar' of bookings created today
        const maiBevetelResult = await Foglalas.sum('Ar', {
            where: {
                Letrehozasdatuma: { [Op.like]: `${today}%` }
            }
        });
        const maiBevetel = maiBevetelResult || 0;

        res.json({
            osszesAuto,
            elerhetoAuto,
            aktivFoglalas,
            maiBevetel
        });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};

exports.getActivities = async (req, res) => {
    try {
        // Combine recent bookings and handovers
        // Since we can't easily UNION with sequelize in a simple way cross-table with different schemas
        // We'll fetch 5 of each and sort in JS

        const bookings = await Foglalas.findAll({
            limit: 5,
            order: [['Letrehozasdatuma', 'DESC']],
            include: [{ model: Auto }, { model: Ugyfel }]
        });

        const handovers = await AutoKibe.findAll({
            limit: 5,
            order: [['elvitel', 'DESC']],
            include: [{ model: Auto }]
        });

        const activities = [
            ...bookings.map(f => ({
                id: f.Foglalasokid,
                type: 'foglalas',
                date: f.Letrehozasdatuma,
                desc: `Foglalás: ${f.Auto.Rendszam} - ${f.Ugyfel.Nev}`
            })),
            ...handovers.map(h => ({
                id: h.Id,
                type: 'kibe',
                date: h.elvitel,
                desc: `Kiadás: ${h.Auto.Rendszam}`
            }))
        ].sort((a, b) => new Date(b.date) - new Date(a.date)).slice(0, 10);

        res.json(activities);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
};
